@echo off
echo Descargando imagenes de filiales oficiales de ASCINALSS...
mkdir assets\filiales 2>nul

echo Descargando La Paz...
curl -s -L -o "assets\filiales\lapaz.png" "https://www.ascinalss.org/ascinalss/filiales_files/ASCINALSS.png"
echo Descargando Camiri...
curl -s -L -o "assets\filiales\camiri.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/camiri.jpg"
echo Descargando Cobija...
curl -s -L -o "assets\filiales\cobija.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/COBIJA.jpg"
echo Descargando Cochabamba...
curl -s -L -o "assets\filiales\cochabamba.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/COCHABAMBA.jpg"
echo Descargando Guayamerin...
curl -s -L -o "assets\filiales\guayamerin.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/GUAYAMERIN.jpg"
echo Descargando Oruro...
curl -s -L -o "assets\filiales\oruro.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/ORURO.jpg"
echo Descargando Potosi...
curl -s -L -o "assets\filiales\potosi.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/POTOSI.jpg"
echo Descargando Puerto Quijarro...
curl -s -L -o "assets\filiales\quijarro.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Pto%%20Quijarro.jpg"
echo Descargando Puerto Suarez...
curl -s -L -o "assets\filiales\suarez.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Pot%%20Suarez.jpg"
echo Descargando Trinidad...
curl -s -L -o "assets\filiales\trinidad.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Trinidad.jpg"
echo Descargando Robore...
curl -s -L -o "assets\filiales\robore.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Robore.jpg"
echo Descargando Rurrenabaque...
curl -s -L -o "assets\filiales\rurrenabaque.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Rurrenabaque.jpg"
echo Descargando Santa Cruz...
curl -s -L -o "assets\filiales\santacruz.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Santa%%20Cruz.jpg"
echo Descargando Sucre...
curl -s -L -o "assets\filiales\sucre.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Sucre.jpg"
echo Descargando Tarija...
curl -s -L -o "assets\filiales\tarija.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Tarija.jpg"
echo Descargando Tupiza...
curl -s -L -o "assets\filiales\tupiza.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Tupiza.jpg"
echo Descargando Villamontes...
curl -s -L -o "assets\filiales\villamontes.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Villamontes.jpg"
echo Descargando Yacuiba...
curl -s -L -o "assets\filiales\yacuiba.jpg" "https://www.ascinalss.org/ascinalss/filiales_files/Yacuiba.jpg"

echo.
echo ¡Descarga de imagenes de filiales con cURL completada con exito!
pause
